// <auto-generated />
namespace ELearning.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class register3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(register3));
        
        string IMigrationMetadata.Id
        {
            get { return "201608230827406_register3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
